name: app_full
description: "App Flutter connectée à une API REST réelle (JWT, cache Hive, mode hors-ligne)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Internationalisation (FR + EN)
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State management
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

  # Réseau
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Persistance locale / cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Stockage sécurisé du token
  flutter_secure_storage: ^9.2.2

  # Images : cache disque + lazy loading automatique
  cached_network_image: ^3.3.1

  # Utilitaires
  equatable: ^2.0.5
  fpdart: ^1.1.0            # Either<Failure, T> pour la gestion d'erreurs
  go_router: ^14.2.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: false
